version: '3.1'
services:
  client:
    build:
      context: ./Client
    container_name: 'grpc-client'
    ports:
      - 3000:3000
  server:
    build:
      context: ./Server
    container_name: 'grpc-server'
    ports:
      - 3001:3001