apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-proyecto2
  namespace: so1p2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment
  minReplicas: 2  
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80