version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_DATABASE: P1SO1
    volumes:
      - ./schemas:/var/lib/mysql
    networks:
      - red1
  backend:
    build:
      context: ./BackEnd
    image: backend
    container_name: backend
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: mysqlpass
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: P1SO1
    privileged: true
    pid: host
    restart: always
    volumes:
      - type: bind
        source: /proc
        target: /proc
    ports:
      - 8000:8000
    networks:
      - red1
  frontend:
    build:
      context: ./FrontEnd
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    links:
      - backend
    restart: always
    ports:
      - 80:80
    networks:
      - red1
networks:
  red1:
    driver: bridge
volumes:
  schemas: